// frontend/svelte/src/components/Breadcrumb.svelte
<script>
  export let segment;
</script>

<style>
  .breadcrumb {
    padding: 8px 0px;
    background-color: unset;
  }
</style>

 <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="blog">blog</a></li>
    <li class="breadcrumb-item active" aria-current={segment === undefined ? 'page' : undefined} >post</li>
  </ol>

// frontend/react-app/src/components/Breadcrumb.tsx
import React from "react";
import "./Breadcrumb.css";

function Breadcrumb(props: any) {
  return (
    <ol className="breadcrumb">
      <li className="breadcrumb-item">
        <a href="/blog">blog</a>
      </li>
      <li
        className="breadcrumb-item active"
        aria-current={true}
      >
        post
      </li>
    </ol>
  );
}

export default Breadcrumb;
