// frontend/svelte/src/routes/blog/index.svelte
<script context="module">
  //export function preload({ params, query }) {
  // return this.fetch(`blog.json`).then(r => r.json()).then(posts => {
  // 	return { posts };
  // });
  // }

  export function preload({ params, query }) {
    return this.fetch("http://localhost:1337/posts", {
      method: "GET",
      withCredentials: true,
      credentials: "include",
      headers: {
        Authorization:
          "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOGNlMTNlMjQwNmMzMDA4NTRiMTQzMSIsImlhdCI6MTU4NjI5MjAxMSwiZXhwIjoxNTg4ODg0MDExfQ.Wicl1PfLf1tWG6Dq8c6SjjtKoj78yX0qOM76HyGryWA",
        "Content-Type": "application/json"
      }
    })
      .then(r => r.json())
      .then(posts => {
        return { posts };
      });
  }
</script>

<script>
  export let posts;
</script>

<style>
  ul {
    margin: 0 0 1em 0;
    line-height: 1.5;
  }
</style>

<!-- <svelte:head>
  <title>Blog</title>
</svelte:head> -->

  <a href="/" class="title">
    <h2>blog</h2>
  </a>

<ul>
  {#each posts as post}
    <!-- we're using the non-standard `rel=prefetch` attribute to
				tell Sapper to load the data for the page as soon as
				the user hovers over the link or taps it, instead of
				waiting for the 'click' event -->
    <li>
      <a rel="prefetch" href="blog/{post.slug}">{post.date}: {post.title}</a>
    </li>
  {/each}
</ul>

// frontend/react-app/src/Blog.tsx
import React, { useState, useEffect } from "react";
import "./Blog.css";

function Blog() {
  const [posts, setPosts] = useState<[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const fetchData = async () => {
      await fetch("http://localhost:1337/posts", {
        method: "GET",
        headers: {
          Authorization:
            "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOGNlMTNlMjQwNmMzMDA4NTRiMTQzMSIsImlhdCI6MTU4NjI5MjAxMSwiZXhwIjoxNTg4ODg0MDExfQ.Wicl1PfLf1tWG6Dq8c6SjjtKoj78yX0qOM76HyGryWA",
          "Content-Type": "application/json"
        }
      }).then(res =>
        res.json().then(res => {
          setPosts(res);
          setLoading(false);
        })
      );
    };
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="spinner-border" role="status">
        <span className="sr-only">Loading...</span>
      </div>
    );
  }

  return (
    <>
      <span className="title">
        <h2>blog</h2>
      </span>
      <section>
        <ul>
          {posts.map((post: any) => (
            <li key={post._id}>
              <a href={`${post.slug}`}>
                {post.date}: {post.title}
              </a>
            </li>
          ))}
        </ul>
      </section>
    </>
  );
}

export default Blog;
