// frontend/svelte/src/routes/projects.svelte
<style>
.project-info {
	max-width: 700px;
}
</style>

<!-- <svelte:head>
	<title>About</title>
</svelte:head> -->

<a href="/" class="title">
  <h2>projects</h2>
</a>

<section>
  <p class="project-info">
    <b>Bot on Tap</b>
    . You need help setting up your own Twitter bot? We are here to help you
    developing and even running and maintaining it as "bot as a service".
  </p>

  <p class="project-info">
    <b>The Lord of the Rings API</b>
    . lorem ipsum.
  </p>

  <p class="project-info"><b>The friendly @femtech_ bot</b></p>

  <p class="project-info"><b>queersplitter.de</b>. lorem</p> 

  <p class="project-info"><b>the false quote generator</b>. fun project</p> 
 
</section>

// frontend/react-app/src/Projects.tsx
import React from "react";
import "./Projects.css";

function Projects() {
  return (
    <>
      <span className="title">
        <h2>projects</h2>
      </span>
      <section>
        <p className="project-info">
          <b>Bot on Tap</b>. You need help setting up your own Twitter bot? We
          are here to help you developing and even running and maintaining it as
          "bot as a service".
        </p>

        <p className="project-info">
          <b>The Lord of the Rings API</b>. lorem ipsum.
        </p>

        <p className="project-info">
          <b>The friendly @femtech_ bot</b>
        </p>

        <p className="project-info">
          <b>queersplitter.de</b>. lorem
        </p>

        <p className="project-info">
          <b>the false quote generator</b>. fun project
        </p>
      </section>
    </>
  );
}

export default Projects;
